// Mocks generated by Mockito 5.4.4 from annotations
// in user_list_app/test/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:user_list_app/core/network/connectivity_service.dart' as _i6;
import 'package:user_list_app/data/datasources/user_local_data_source.dart'
    as _i5;
import 'package:user_list_app/data/datasources/user_remote_data_source.dart'
    as _i3;
import 'package:user_list_app/data/models/user_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUsersResponseModel_0 extends _i1.SmartFake
    implements _i2.UsersResponseModel {
  _FakeUsersResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i3.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UsersResponseModel> getUsers({
    required int? page,
    required int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue:
            _i4.Future<_i2.UsersResponseModel>.value(_FakeUsersResponseModel_0(
          this,
          Invocation.method(
            #getUsers,
            [],
            {
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i4.Future<_i2.UsersResponseModel>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i5.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cacheUsers(
    _i2.UsersResponseModel? usersResponse,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUsers,
          [
            usersResponse,
            page,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UsersResponseModel?> getCachedUsers(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedUsers,
          [page],
        ),
        returnValue: _i4.Future<_i2.UsersResponseModel?>.value(),
      ) as _i4.Future<_i2.UsersResponseModel?>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasConnection() => (super.noSuchMethod(
        Invocation.method(
          #hasConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
